/**
 * Conformance suite for the format layer.
 *
 * Two tiers of samples:
 *
 *   corpus/owned/   generated by scripts/make-fixtures.ts, committed, original
 *                   content. These gate the build: format, entry count, and the
 *                   exact set of unknown source fields are all asserted.
 *   corpus/local/   real published world books you drop in yourself (git-ignored).
 *                   These never fail the suite for unknown fields; instead the
 *                   unknown fields are reported, which is how new vocabulary gets
 *                   discovered and then mapped.
 *
 * For every sample:
 *   1. parse      - format detection, entry count, warnings
 *   2. round trip - serialize(parse(x)) deep-equals x (all unknown fields intact)
 *   3. edit       - a field write reaches the right source key and survives re-parse
 *   4. add/remove - adding then removing an entry restores the document exactly
 *
 * Run: npm run test:conformance
 */

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { parseCardFile, writeCardPNG } from '../src/formats/character-card.ts';
import {
  addEntry,
  detectWorldFormat,
  fieldCoverage,
  parseWorldInfo,
  removeEntry,
  serializeWorld,
  setEntryField,
  toStNative,
  unknownFieldsOf,
  worldsDeepEqual,
  type CoverageReport,
} from '../src/formats/world-info.ts';
import type { World } from '../src/formats/types.ts';

const here = dirname(fileURLToPath(import.meta.url));
const ownedDir = resolve(here, '..', 'corpus', 'owned');
const localDir = resolve(here, '..', 'corpus', 'local');

interface ManifestSample {
  file: string;
  format: string;
  entries: number;
  unknownFields?: string[];
  note?: string;
}

let failures = 0;
let checks = 0;

function check(ok: boolean, label: string, detail = ''): void {
  checks++;
  if (ok) return;
  failures++;
  console.log(`  FAIL  ${label}${detail ? ` :: ${detail}` : ''}`);
}

function eq<T>(actual: T, expected: T, label: string): void {
  const a = JSON.stringify(actual);
  const b = JSON.stringify(expected);
  check(a === b, label, `got ${a}, want ${b}`);
}

function section(title: string): void {
  console.log(`\n=== ${title} ===`);
}

const worlds: World[] = [];

// ---------------------------------------------------------------------------
// Shared per-sample assertions
// ---------------------------------------------------------------------------

/**
 * Round trip, edit-through, and add/remove for a world document.
 * `expectedEntries` is only checked when the caller knows it.
 */
function exerciseWorld(options: {
  label: string;
  bytes: Buffer;
  format: World['sourceFormat'];
  expectedEntries?: number;
  declaredUnknown?: string[];
}): World {
  const original = JSON.parse(options.bytes.toString('utf8')) as unknown;
  const detected = detectWorldFormat(original);
  check(detected === options.format, 'format detection', `got ${detected}, want ${options.format}`);

  const parse = () => parseWorldInfo(JSON.parse(options.bytes.toString('utf8')), {
    id: options.label,
    format: options.format,
  });

  const { world, warnings } = parse();
  if (options.expectedEntries !== undefined) {
    eq(world.entries.length, options.expectedEntries, 'entry count');
  }

  const unknown = unknownFieldsOf(world);
  if (options.declaredUnknown === undefined) {
    // Real-world sample: report, never fail. This is the discovery channel.
    if (unknown.length > 0) {
      console.log(`  note: ${unknown.length} unrecognised source field(s): ${unknown.join(', ')}`);
    }
  } else {
    eq(unknown, [...options.declaredUnknown].sort(), 'unknown source fields are exactly the declared set');
  }

  console.log(
    `  detected=${world.sourceFormat} entries=${world.entries.length}` +
      ` scanDepth=${world.scanDepth ?? '-'} tokenBudget=${world.tokenBudget ?? '-'}` +
      ` recursive=${world.recursiveScanning ?? '-'}` +
      (warnings.length ? ` warnings=${warnings.length}` : '') +
      (unknown.length ? ` unknown=${unknown.join('|')}` : ''),
  );

  // Round trip.
  check(
    worldsDeepEqual(original, JSON.parse(serializeWorld(world))),
    'round trip is lossless',
    'serialized output differs from the source document',
  );

  const first = world.entries[0];
  if (first) {
    // Field writes land on the right source key and survive a re-parse.
    const probe = parse().world;
    const target = probe.entries[0]!;
    setEntryField(probe, target.uid, 'comment', 'CONFORMANCE_PROBE');
    setEntryField(probe, target.uid, 'probability', 42);
    setEntryField(probe, target.uid, 'constant', true);
    setEntryField(probe, target.uid, 'position', 3);

    const after = parseWorldInfo(JSON.parse(serializeWorld(probe)), {
      id: options.label,
      format: options.format,
    }).world.entries.find((entry) => entry.uid === target.uid);

    check(after !== undefined, 'edited entry survives re-parse');
    if (after) {
      eq(after.comment, 'CONFORMANCE_PROBE', 'comment write');
      eq(after.probability, 42, 'probability write');
      eq(after.constant, true, 'constant write');
      eq(after.position, 3, 'position write');
    }

    // Editing must not drop any field it did not touch.
    const beforeKeys = Object.keys(target.raw);
    const afterKeys = Object.keys(
      parseWorldInfo(JSON.parse(serializeWorld(probe)), {
        id: options.label,
        format: options.format,
      }).world.entries[0]!.raw,
    );
    const lost = beforeKeys.filter((key) => !afterKeys.includes(key));
    check(lost.length === 0, 'edits do not drop unknown fields', `lost: ${lost.join(', ')}`);

    // Add then remove restores the document exactly.
    const scratch = parse().world;
    const added = addEntry(scratch, { comment: 'TEMP', content: 'TEMP', key: ['temp'] });
    eq(scratch.entries.length, world.entries.length + 1, 'addEntry grows the list');
    removeEntry(scratch, added.uid);
    eq(scratch.entries.length, world.entries.length, 'removeEntry shrinks the list');
    check(
      worldsDeepEqual(original, JSON.parse(serializeWorld(scratch))),
      'add+remove restores the document exactly',
    );

    // A brand-new entry must be readable again in *every* field, in every
    // format: writing only the fields a source happens to map is how a new
    // entry silently loses its insertion position.
    const freshWorld = parse().world;
    const fresh = addEntry(freshWorld, {
      comment: 'FRESH',
      content: 'FRESH CONTENT',
      key: ['fresh-key'],
      keysecondary: ['fresh-secondary'],
      constant: true,
      selectiveLogic: 2,
      order: 123,
      position: 0,
      depth: 2,
      role: 1,
      probability: 33,
      group: 'fresh-group',
      sticky: 4,
    });
    const reread = parseWorldInfo(JSON.parse(serializeWorld(freshWorld)), {
      id: options.label,
      format: options.format,
    }).world.entries.find((entry) => entry.uid === fresh.uid);

    check(reread !== undefined, 'a newly created entry re-parses');
    if (reread) {
      eq(reread.comment, 'FRESH', 'new entry: comment');
      eq(reread.content, 'FRESH CONTENT', 'new entry: content');
      eq(reread.key, ['fresh-key'], 'new entry: primary keys');
      eq(reread.keysecondary, ['fresh-secondary'], 'new entry: secondary keys');
      eq(reread.constant, true, 'new entry: constant');
      eq(reread.selectiveLogic, 2, 'new entry: selectiveLogic');
      eq(reread.order, 123, 'new entry: order');
      eq(reread.position, 0, 'new entry: position');
      eq(reread.depth, 2, 'new entry: depth');
      eq(reread.role, 1, 'new entry: role');
      eq(reread.probability, 33, 'new entry: probability');
      eq(reread.group, 'fresh-group', 'new entry: group');
      eq(reread.sticky, 4, 'new entry: sticky');
    }
  }

  return world;
}

// ---------------------------------------------------------------------------
// Tier 1: owned fixtures (assertive)
// ---------------------------------------------------------------------------

const manifest = JSON.parse(readFileSync(join(ownedDir, 'manifest.json'), 'utf8')) as {
  samples: ManifestSample[];
};

section(`owned fixtures (${manifest.samples.length})`);

for (const sample of manifest.samples) {
  const path = join(ownedDir, sample.file);
  const bytes = readFileSync(path);
  console.log(`\n-- ${sample.file}  [${sample.format}]`);
  if (sample.note) console.log(`   ${sample.note}`);

  if (sample.format === 'character-card') {
    const { card, image } = parseCardFile(bytes, 'osk');
    check(card.name.length > 0, 'card name present', card.name);
    check(sample.entries !== undefined, 'manifest declares the book size');
    eq(card.books[0]?.entries.length ?? 0, sample.entries, 'embedded book size');
    console.log(`   spec=${card.spec} name="${card.name}" books=${card.books.length} warnings=${card.warnings.length}`);

    if (image !== null) {
      // A card PNG must survive a write/read cycle with identical fields.
      const again = parseCardFile(writeCardPNG(image, card), 'osk');
      eq(again.card.name, card.name, 'png rewrite keeps name');
      eq(again.card.first_mes, card.first_mes, 'png rewrite keeps first_mes');
      eq(again.card.alternate_greetings, card.alternate_greetings, 'png rewrite keeps greetings');
      eq(again.card.spec, 'v3', 'ccv3 chunk reads back as v3');
      eq(
        again.card.books[0]?.entries.length ?? 0,
        card.books[0]?.entries.length ?? 0,
        'png rewrite keeps the embedded book',
      );
    }
    if (card.books[0]) worlds.push(card.books[0]);
    continue;
  }

  worlds.push(exerciseWorld({
    label: sample.file,
    bytes,
    format: sample.format as World['sourceFormat'],
    expectedEntries: sample.entries,
    declaredUnknown: sample.unknownFields ?? [],
  }));
}

// ---------------------------------------------------------------------------
// Tier 2: local real-world samples (informative)
// ---------------------------------------------------------------------------

section('local samples');
if (!existsSync(localDir)) {
  console.log('  none (drop real world books into corpus/local/ to check them)');
} else {
  const files: string[] = [];
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir)) {
      const path = join(dir, name);
      if (statSync(path).isDirectory()) walk(path);
      else if (name.endsWith('.json') && name !== 'manifest.json') files.push(path);
    }
  };
  walk(localDir);
  console.log(`  ${files.length} file(s) found`);

  for (const path of files) {
    const label = relative(localDir, path).replace(/\\/g, '/');
    const bytes = readFileSync(path);
    console.log(`\n-- ${label}`);
    try {
      const format = detectWorldFormat(JSON.parse(bytes.toString('utf8')));
      if (format === null) {
        check(false, `${label} is a recognisable world book`, 'format detection returned null');
        continue;
      }
      worlds.push(exerciseWorld({ label, bytes, format }));
    } catch (error) {
      check(false, `${label} parses`, (error as Error).message);
    }
  }
}

// ---------------------------------------------------------------------------
// Coverage report
// ---------------------------------------------------------------------------

section('field coverage');
const coverage: CoverageReport = fieldCoverage(worlds);
for (const [format, bucket] of Object.entries(coverage.perFormat)) {
  console.log(`\n  ${format}  (${bucket.entries} entries)`);
  console.log(`    mapped  (${bucket.mapped.length}): ${bucket.mapped.join(', ') || '-'}`);
  console.log(`    ignored (${bucket.ignored.length}): ${bucket.ignored.join(', ') || '-'}`);
  console.log(`    UNKNOWN (${bucket.unknown.length}): ${bucket.unknown.join(', ') || '-'}`);
}

// Every field seen must be either mapped or knowingly ignored. The fixtures
// declare their deliberate unknowns, so anything else here is a real gap.
const declared = new Set(manifest.samples.flatMap((sample) => sample.unknownFields ?? []));
const unexplained = [...new Set(Object.values(coverage.perFormat).flatMap((bucket) => bucket.unknown))]
  .filter((field) => !declared.has(field));
check(
  unexplained.length === 0,
  'every source field is mapped, ignored, or declared as opaque',
  unexplained.join(', '),
);
console.log(`\n  declared opaque fields: ${[...declared].sort().join(', ') || '-'}`);
console.log(`  unexplained fields    : ${unexplained.join(', ') || '-'}`);

// ---------------------------------------------------------------------------
// Cross-format export
// ---------------------------------------------------------------------------

section('export as ST-native');
for (const world of worlds) {
  const reparsed = parseWorldInfo(JSON.parse(JSON.stringify(toStNative(world))), {
    id: `${world.id}:st`,
    format: 'st-native',
  });
  eq(reparsed.world.entries.length, world.entries.length, `${world.sourceFormat} -> st-native keeps all entries`);
  const first = world.entries[0];
  const firstOut = reparsed.world.entries.find((entry) => entry.uid === first?.uid);
  if (first && firstOut) {
    check(
      firstOut.content === first.content && firstOut.key.join('|') === first.key.join('|'),
      `${world.sourceFormat} -> st-native keeps first entry content and keys`,
    );
  }
}

// ---------------------------------------------------------------------------

console.log(`\n${failures === 0 ? 'ALL PASS' : 'FAILURES'}  checks=${checks} failed=${failures}`);
process.exit(failures === 0 ? 0 : 1);
