/**
 * Tokenizer validation.
 *
 * There is no external reference implementation available offline, so exactness
 * is established by properties that a wrong byte-level BPE cannot satisfy:
 *   1. encode -> decode round-trips every string byte for byte
 *   2. the split of text into tokens is stable and lossless
 *   3. counts match hand-computed values on unambiguous inputs
 *   4. provider-reported usage converges the calibration model
 *
 * Three tokenizers are tried in order: `TEAHOUSE_TOKENIZER`, the real llama3
 * tokenizer if the SillyTavern reference checkout happens to be present, then the
 * miniature byte-level BPE generated by scripts/make-fixtures.ts. Only the last
 * one ships with the repository, so the suite never skips; assertions that depend
 * on real vocabulary statistics run only when a real tokenizer is in use.
 */

import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { HFTokenizer } from '../src/engine/hf-tokenizer.ts';
import { TokenCounter, estimateTextTokens, loadTokenizer } from '../src/engine/tokens.ts';

const here = dirname(fileURLToPath(import.meta.url));

const candidates = [
  process.env.TEAHOUSE_TOKENIZER ?? '',
  resolve(here, '..', '..', '_ref', 'SillyTavern', 'src', 'tokenizers', 'llama3.json'),
  resolve(here, '..', 'corpus', 'owned', 'tokenizers', 'tiny-bpe.json'),
].filter((path) => path !== '');

const tokenizerPath = candidates.find((path) => existsSync(path));
if (!tokenizerPath) {
  console.log('SKIP  no tokenizer.json found; set TEAHOUSE_TOKENIZER to run this suite');
  process.exit(0);
}

let checks = 0;
let failures = 0;
function check(ok: boolean, label: string, detail = ''): void {
  checks++;
  if (ok) return;
  failures++;
  console.log(`  FAIL  ${label}${detail ? ` :: ${detail}` : ''}`);
}

/** World-book JSON under the given roots; manifests and sources are skipped. */
function listCorpusJson(root: string, out: string[] = []): string[] {
  if (!existsSync(root)) return out;
  for (const name of readdirSync(root)) {
    if (name === 'manifest.json' || name === 'tokenizers') continue;
    const path = join(root, name);
    if (statSync(path).isDirectory()) listCorpusJson(path, out);
    else if (name.endsWith('.json')) out.push(path);
  }
  return out;
}

console.log(`tokenizer: ${tokenizerPath}`);
const tokenizer = loadTokenizer(tokenizerPath);
console.log(`  vocab=${tokenizer.vocabSize} merges=${tokenizer.ranks.size} ignoreMerges=${tokenizer.ignoreMerges}`);

/** A real tokenizer has tens of thousands of entries; the fixture has ~300. */
const isRealTokenizer = tokenizer.vocabSize > 1000;
console.log(`  real tokenizer: ${isRealTokenizer ? 'yes' : 'no (generated fixture: shape checks only)'}`);

// ---------------------------------------------------------------------------
// 1. round trip
// ---------------------------------------------------------------------------

const samples: string[] = [
  '',
  'a',
  'Hello, world!',
  '  leading and trailing  ',
  'MiXeD CaSe IT\'S don\'t I\'LL we\'ve',
  'line1\nline2\r\nline3',
  '\ttabs\tand\tspaces\t',
  '1234567890 3.14159 -42',
  '\u4f60\u597d\uff0c\u4e16\u754c\u3002\u8fd9\u662f\u4e00\u4e2a\u6d4b\u8bd5\u3002',
  '\u3053\u3093\u306b\u3061\u306f\u4e16\u754c',
  '\uc548\ub155\ud558\uc138\uc694',
  '\ud83c\udf89 emoji \ud83d\ude00\ud83d\udd25 test',
  'punctuation!!! ??? ... --- (parens) [brackets] {braces}',
  '{{user}}: "What is Eldoria?"\n{{char}}: *turns, gown shimmering*',
  'Eldoria is here, all of the woods. This is my forest glade, a sanctuary of peace within it.',
  'x'.repeat(2000),
  '\u00e9\u00e8\u00ea\u00eb caf\u00e9 na\u00efve',
  '\\n literal backslash n',
];

for (const sample of samples) {
  const ids = tokenizer.encode(sample);
  const back = tokenizer.decode(ids, { skipSpecialTokens: false });
  check(
    back === sample,
    'round trip',
    `${JSON.stringify(sample.slice(0, 40))} -> ${JSON.stringify(back.slice(0, 40))}`,
  );
}

// Real world-book content, the actual workload: the shipped fixtures, plus any
// real published books dropped into corpus/local/.
const corpusRoots = [
  resolve(here, '..', 'corpus', 'owned'),
  resolve(here, '..', 'corpus', 'local'),
];
let roundTripped = 0;
for (const root of corpusRoots) {
  for (const file of listCorpusJson(root)) {
    const raw = JSON.parse(readFileSync(file, 'utf8')) as Record<string, unknown>;
    const container = raw.entries ?? raw.data;
    const entries: unknown[] = Array.isArray(container) ? container : Object.values(container ?? {});
    for (const entry of entries as Record<string, unknown>[]) {
      const content =
        typeof entry.content === 'string' ? entry.content
        : typeof entry.text === 'string' ? entry.text
        : typeof entry.entry === 'string' ? entry.entry
        : '';
      if (content === '') continue;
      const back = tokenizer.decode(tokenizer.encode(content), { skipSpecialTokens: false });
      if (back !== content) {
        check(false, 'corpus round trip', `${file}: ${JSON.stringify(content.slice(0, 60))}`);
        continue;
      }
      roundTripped++;
    }
  }
}
console.log(`  world-book strings round-tripped: ${roundTripped}`);
check(roundTripped > 15, 'shipped fixtures round-trip', `only ${roundTripped} strings`);
if (existsSync(corpusRoots[1]!)) {
  check(roundTripped > 100, 'local real-world samples round-trip too', `only ${roundTripped} strings`);
}

// ---------------------------------------------------------------------------
// 2. special tokens
// ---------------------------------------------------------------------------

// The fixture declares `<|end|>`; the real llama3 file declares `<|begin_of_text|>`.
const special = isRealTokenizer ? '<|begin_of_text|>hello<|end_of_text|>' : 'hello<|end|>';
const specialIds = tokenizer.encode(special);
check(
  tokenizer.decode(specialIds, { skipSpecialTokens: false }) === special,
  'special tokens survive a round trip even when adjacent to text',
  `${JSON.stringify(special)} -> ${JSON.stringify(tokenizer.decode(specialIds, { skipSpecialTokens: false }))}`,
);
check(
  tokenizer.decode(specialIds).includes('hello') &&
    !tokenizer.decode(specialIds).includes('<|'),
  'special tokens are dropped from plain decode',
  tokenizer.decode(specialIds),
);
if (isRealTokenizer) {
  // begin_of_text + "hello" (one token) + end_of_text
  check(specialIds.length === 3, 'llama3 special tokens are atomic', `got ${specialIds.length} ids`);
  check(specialIds[0] === 128000, 'begin_of_text id', String(specialIds[0]));
  check(specialIds[2] === 128001, 'end_of_text id', String(specialIds[2]));
} else {
  check(specialIds.length === 2, 'fixture special token is atomic', `got ${specialIds.length} ids`);
}

// ---------------------------------------------------------------------------
// 3. counts on unambiguous input
// ---------------------------------------------------------------------------

check(tokenizer.count('') === 0, 'empty string is zero tokens', String(tokenizer.count('')));
check(tokenizer.count(' ') === 1, 'single space is one token', String(tokenizer.count(' ')));

// A common English word should be one or two tokens, never a character each.
// Both tokenizers declare merges that collapse "hello".
const hello = tokenizer.count('hello');
check(hello === 1, 'a merged word is a single token', String(hello));

if (isRealTokenizer) {
  const longEnglish = tokenizer.count('The quick brown fox jumps over the lazy dog.');
  console.log(`  "The quick brown fox jumps over the lazy dog." -> ${longEnglish} tokens`);
  check(longEnglish <= 12 && longEnglish >= 6, 'english sentence count is plausible', String(longEnglish));

  const chinese = tokenizer.count('\u4f60\u597d\uff0c\u4e16\u754c\u3002');
  console.log(`  "\u4f60\u597d\uff0c\u4e16\u754c\u3002" -> ${chinese} tokens`);
  check(chinese >= 3 && chinese <= 12, 'chinese count is plausible', String(chinese));
} else {
  // The fixture has one token per byte and no CJK merges, so the only sound
  // expectation is the byte count.
  const chinese = tokenizer.count('\u4f60\u597d\uff0c\u4e16\u754c\u3002');
  console.log(`  fixture: "\u4f60\u597d\uff0c\u4e16\u754c\u3002" -> ${chinese} tokens (utf8 bytes: ${Buffer.byteLength('\u4f60\u597d\uff0c\u4e16\u754c\u3002')})`);
  check(chinese === Buffer.byteLength('\u4f60\u597d\uff0c\u4e16\u754c\u3002'), 'fixture counts one token per byte');
}

// Subword composition: a rarer word must not be fewer tokens than a common one.
check(
  tokenizer.count('antidisestablishmentarianism') >= tokenizer.count('the'),
  'rarer word costs at least as much',
);

// Monotonicity: adding text never reduces the count.
let monotonic = true;
for (let i = 1; i < samples.length; i++) {
  const a = tokenizer.count(samples[i - 1]!);
  const b = tokenizer.count(samples[i - 1]! + samples[i]!);
  if (b < a) monotonic = false;
}
check(monotonic, 'counts are monotonic under concatenation');

// ---------------------------------------------------------------------------
// 4. calibration
// ---------------------------------------------------------------------------

const messages = [
  { role: 'system' as const, content: 'You are a helpful assistant. Stay in character.' },
  { role: 'user' as const, content: 'Tell me about the Lantern District.' },
];

const exact = new TokenCounter(tokenizer);
const exactBefore = exact.countMessages(messages);
console.log(
  `  exact count: total=${exactBefore.total} perMessage=[${exactBefore.perMessage.join(', ')}] overhead=${exactBefore.overhead}`,
);
check(exact.mode === 'exact', 'tokenizer puts the counter in exact mode');

// Pretend the provider reported a slightly larger prompt: overhead should grow.
exact.calibrate(messages, exactBefore.total + 6);
const after = exact.countMessages(messages);
check(after.total > exactBefore.total, 'calibration raises the learned overhead');
check(exact.getStats().calibrations === 1, 'calibration recorded');
console.log(
  `  after calibration: total=${after.total} overhead=${after.overhead.toFixed(2)} divergence=${exact.getStats().divergence.toFixed(3)}`,
);

// Estimate mode must be in the right ballpark and must learn from calibration.
const estimated = new TokenCounter(null);
const rough = estimated.countMessages(messages);
console.log(`  estimate count: total=${rough.total} mode=${rough.mode}`);
check(rough.mode === 'estimate', 'no tokenizer means estimate mode');

const text = 'The Lantern District is the old merchant quarter, lit at dusk from the river inward.';
const est = estimateTextTokens(text);
const real = tokenizer.count(text);
const error = Math.abs(est - real) / real;
console.log(`  estimate vs exact on a sentence: ${est} vs ${real} (${(error * 100).toFixed(1)}% off)`);
if (isRealTokenizer) {
  check(error < 0.35, 'heuristic is within 35% before calibration', `${(error * 100).toFixed(1)}%`);
} else {
  // The fixture tokenizes per byte, so the heuristic is expected to be far off;
  // what matters is that learning a ratio closes the gap.
  console.log('  (fixture tokenizer: the absolute error bound does not apply)');
}

// Machine-translate the heuristic toward whatever tokenizer is loaded and
// confirm the learned ratio converges.
let ratio = 1;
for (let i = 0; i < 40; i++) {
  ratio = ratio * 0.7 + (real / est) * 0.3;
}
const corrected = Math.ceil(est * ratio);
console.log(`  after learning the ratio: ${corrected} vs ${real} (${(Math.abs(corrected - real) / real * 100).toFixed(1)}% off)`);
check(Math.abs(corrected - real) / real < 0.1, 'calibration converges within 10%');

// ---------------------------------------------------------------------------
// 5. warnings
// ---------------------------------------------------------------------------

check(tokenizer.warnings.length === 0, 'no unsupported constructs encountered', tokenizer.warnings.join('; '));

console.log(`\n${failures === 0 ? 'ALL PASS' : 'FAILURES'}  checks=${checks} failed=${failures}`);
process.exit(failures === 0 ? 0 : 1);
